// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {contracts} from '../models';
import {context} from '../models';

export function DeleteToDo(arg1:number):Promise<void>;

export function EditToDo(arg1:number,arg2:contracts.ToDoEditReq):Promise<void>;

export function GetToDo(arg1:number):Promise<contracts.ToDoRes>;

export function GetToDoList():Promise<any>;

export function SaveToDo(arg1:contracts.ToDoReq):Promise<number>;

export function Startup(arg1:context.Context):Promise<void>;
